version: 2


python:
  version: "3.7"
    install:
      - method: pip
        path: .
        extra_requirements:
          - docs
      - method: pip
        path: package

sphinx:
  fail_on_warning: true   
  

formats:
  - pdf
  - epub

